version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magento-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - mysql
      - elasticsearch
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=magento
    networks:
      - magento-net

  mysql:
    image: mysql:8.0
    container_name: magento-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - magento-net

  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: magento-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - magento-net

  redis:
    image: redis:6.2
    container_name: magento-redis
    ports:
      - "6379:6379"
    networks:
      - magento-net

  nginx:
    image: nginx:latest
    container_name: magento-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - magento-net

volumes:
  mysql-data:

networks:
  magento-net:
    driver: bridge
